[package]
name = "bank-payments-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.1"
serde = { version = "1.0.217", features = ["derive"] }
thiserror = "2.0.11"
rust_decimal = "1.36.0"
rust_decimal_macros = "1.36.0"